### PR TITLE
Several improvements to the Makefile

### PR DESCRIPTION
**Pull request by arcctgx**
Hi,

I was recently looking at your `Makefile`, and I think some things can be handled in a better way. In my pull request:
- Targets for creating object files are improved. Current version relies on implicit GNU Make rules for creating object files, my changes are defining the recipes and their dependencies explicitly.
- Dependencies between object files are specified so that parallel invocation of `make` works fine.
- `.PHONY` targets are marked as such.
- `clean` target is modified to use built-in `$(RM)`.
- `install` target is now installing the man pages too.

### CODE REVIEW

**Comment by arcctgx** [comment]
Bah, I didn't look at the already opened PRs before submitting mine. My PR addresses the same issues as #5 and #6 of @samueloph.

**Comment by joswr1ght** [comment]
I merged #5 and #6. If you don't mind resolving the conflicts I'll merge your additional changes as well. Thank you!

**Comment by arcctgx** [comment]
I don't mind at all, but I need to know how you want this to be done.
Do you want me to leave the existing recipes as they are after integration of #5, and only add the part that installs the manuals?
Or do you want me to change the recipes as well, like in my original PR?

**Comment by arcctgx** [comment]
OK, that's how I would do it. I hope you find it acceptable.

**Pull request closed without merging**
